version: '3.9'

services:
  mariadb:
    image: mariadb
    restart: always
    container_name: ${DK_PROJECT_NAME}_mariadb
    volumes:
      - ${DK_VOLUMES}/mariadb:/var/lib/mysql
    ports:
      - "${MARIADB_PORT}:${MARIADB_PORT}"
    environment:
      MARIADB_ROOT_HOST: ${MARIADB_ROOT_HOST}
      MARIADB_MYSQL_LOCALHOST_USER: ${MARIADB_MYSQL_LOCALHOST_USER}
      MARIADB_PORT: ${MARIADB_PORT}
      MARIADB_USER: ${MARIADB_USER}
      MARIADB_PASSWORD: ${MARIADB_PASSWORD}
      MARIADB_DATABASE: ${MARIADB_DATABASE}
      MARIADB_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD}
    networks:
      - backend

  api:
    build:
      context: ./projects/coopers-api
      args:
        DK_UID: ${DK_UID}
        DK_GID: ${DK_GID}
    container_name: ${DK_PROJECT_NAME}_api
    ports:
      - "${API_PORT}:3001"
      - "9240:9240"
    environment:
      NODE_ENV: ${DK_ENVIRONMENT}
      API_PORT: ${API_PORT}
      API_JWT_SECRET: ${API_JWT_SECRET}
      API_JWT_EXPIRATION: ${API_JWT_EXPIRATION}
      MARIADB_MYSQL_LOCALHOST_USER: ${MARIADB_MYSQL_LOCALHOST_USER}
      MARIADB_PORT: ${MARIADB_PORT}
      MARIADB_USER: ${MARIADB_USER}
      MARIADB_PASSWORD: ${MARIADB_PASSWORD}
      MARIADB_DATABASE: ${MARIADB_DATABASE}
      STORAGE_PATH: '/mnt/storagefs'
    volumes:
      - ${PWD}/projects/coopers-api:/home/node/project
      - ${DK_STORAGE_FS}:/mnt/storagefs
    depends_on:
      mariadb:
        condition: service_started
    networks:
      - backend
    command: [ "npm", "run", "start:debug" ]

  front:
    build:
      context: ./projects/coopers-front
      args:
        DK_UID: ${DK_UID}
        DK_GID: ${DK_GID}
    container_name: ${DK_PROJECT_NAME}_front
    ports:
      - "${FRONTEND_PORT}:3000"
    volumes:
      - ${PWD}/projects/coopers-front:/home/node/project
    networks:
      - backend
    command: [ "npm", "run", "dev" ]

networks:
  backend:
    driver: bridge
